#!/usr/bin/env node
// Build subjects/<slug>/display.json — the Hebrew text the app actually renders.
//
//   node scripts/build-display.mjs mechonaut
//   node scripts/build-display.mjs --all
//
// questions.json stays the untouched source of truth. This is a derived layer:
// the same words, with the PDF's spacing damage repaired, the technical terms
// tagged, and the handful of genuinely destroyed options restored by hand from
// subjects/<slug>/text-overrides.json.

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { findTerms } from './lib/hebrew.mjs';
import { assertLettersPreserved, buildVocabulary, repairText } from './lib/repair.mjs';
import { SUBJECTS_DIR, listSubjects, readJson, writeJson } from './lib/subjects.mjs';

const OPTION_KEYS = ['א', 'ב', 'ג', 'ד'];

const argv = process.argv.slice(2);
const slugs = argv.includes('--all')
  ? listSubjects({ activeOnly: true })
  : argv.filter((a) => !a.startsWith('-'));

if (slugs.length === 0) {
  console.error('usage: node scripts/build-display.mjs <slug> [...] | --all');
  process.exit(1);
}

for (const slug of slugs) build(slug);

function build(slug) {
  const dir = join(SUBJECTS_DIR, slug);
  const path = (f) => join(dir, f);

  if (!existsSync(path('terms.json'))) {
    throw new Error(`${slug}: no terms.json — run "node scripts/build-terms.mjs ${slug}" first`);
  }

  const { questions } = readJson(path('questions.json'));
  const dictionary = readJson(path('terms.json')).terms;
  const overrides = existsSync(path('text-overrides.json')) ? readJson(path('text-overrides.json')) : {};
  const byId = overrides.questions ?? {};

  const vocab = buildVocabulary({
    cheatsheet: readFileSync(path('cheatsheet.md'), 'utf8'),
    corpus: questions.flatMap((q) => [q.question, ...Object.values(q.options)]),
  });
  for (const w of overrides.vocabulary ?? []) vocab.add(w);

  const report = [];
  const unresolved = [];

  const out = questions.map((q) => {
    const ov = byId[String(q.id)] ?? {};
    const reconstructed = new Set(ov.reconstructed ?? []);

    const render = (field, original, replacement) => {
      if (replacement !== undefined) {
        // Hand-authored: letters legitimately differ, so the invariant does not
        // apply. Recorded in the report as a reconstruction, not a repair.
        report.push({ id: q.id, field, from: original, to: replacement, kind: 'reconstructed' });
        return replacement;
      }
      const r = repairText(original, vocab);
      assertLettersPreserved(original, r.text, `q${q.id} ${field}`);
      for (const rep of r.repairs) {
        report.push({ id: q.id, field, from: rep.from, to: rep.to, kind: rep.confident ? 'repair' : 'repair?' });
      }
      for (const u of r.unresolved) unresolved.push({ id: q.id, field, text: u });
      return r.text;
    };

    const question = render('question', q.question, reconstructed.has('question') ? ov.question : undefined);
    const options = Object.fromEntries(
      OPTION_KEYS.map((k) => [k, render(`opt ${k}`, q.options[k], ov.options?.[k])]),
    );

    const haystack = [question, ...Object.values(options)].join(' \n ');
    return {
      id: q.id,
      question,
      options,
      terms: findTerms(haystack, dictionary),
      questionTerms: findTerms(question, dictionary),
      ...(reconstructed.size ? { reconstructed: [...reconstructed] } : {}),
      ...(ov.note ?? q.note ? { note: ov.note ?? q.note } : {}),
      ...(ov.issue ? { issue: ov.issue } : {}),
    };
  });

  writeJson(path('display.json'), {
    schema: 1,
    subject: slug,
    generatedFrom: ['questions.json', 'terms.json', 'text-overrides.json'],
    count: out.length,
    questions: out,
  });
  writeFileSync(path('repairs.report.txt'), formatReport(slug, report, unresolved), 'utf8');

  const counts = report.reduce((a, r) => ({ ...a, [r.kind]: (a[r.kind] ?? 0) + 1 }), {});
  const flagged = out.filter((q) => q.issue).map((q) => q.id);
  const untagged = out.filter((q) => q.terms.length === 0).map((q) => q.id);

  console.log(
    `✓ ${slug}: ${out.length} questions · ` +
      `${counts.repair ?? 0} repaired, ${counts['repair?'] ?? 0} by morphology, ` +
      `${counts.reconstructed ?? 0} reconstructed`,
  );
  console.log(
    `  terms tagged on ${out.length - untagged.length}/${out.length}` +
      (untagged.length ? ` — none on: ${untagged.join(', ')}` : ''),
  );
  if (unresolved.length) {
    console.log(`  ⚠ ${unresolved.length} fragment(s) left unrepaired — see repairs.report.txt`);
  }
  if (flagged.length) console.log(`  ⚠ damaged in the source PDF: ${flagged.join(', ')}`);
}

function formatReport(slug, report, unresolved) {
  const lines = [
    `Text repairs for subject "${slug}"`,
    `Generated by scripts/build-display.mjs — do not edit.`,
    ``,
    `repair        automatic, vocabulary-confirmed; letters unchanged`,
    `repair?       automatic, decided by Hebrew morphology; letters unchanged`,
    `reconstructed hand-authored in text-overrides.json; letters DO differ`,
    ``,
  ];
  for (const r of report) {
    lines.push(`${r.kind.padEnd(14)} q${String(r.id).padEnd(4)} ${r.field.padEnd(10)} ${r.from}  ->  ${r.to}`);
  }
  if (unresolved.length) {
    lines.push('', 'LEFT UNREPAIRED (fragments the vocabulary could not confirm):');
    for (const u of unresolved) lines.push(`  q${String(u.id).padEnd(4)} ${u.field.padEnd(10)} ${u.text}`);
  }
  return lines.join('\n') + '\n';
}
