#!/usr/bin/env node
// Write dist/sw.js after a build: a service worker that precaches the whole
// app — shell, every hashed chunk (the subject content is bundled as lazy
// chunks under /assets), manifest, icons — so the app works fully offline
// from the first visit, including subjects never opened while online.
//
// Runs as part of `npm run build`. The cache name is derived from the content
// of the file list, so an unchanged rebuild keeps the same cache and a real
// change swaps it atomically on activate.

import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DIST = join(ROOT, 'dist');

if (!existsSync(join(DIST, 'index.html'))) {
  console.error('✗ dist/index.html not found — run vite build first');
  process.exit(1);
}

const assets = readdirSync(join(DIST, 'assets')).map((f) => `/assets/${f}`);
const statics = readdirSync(DIST)
  .filter((f) => f.endsWith('.png') || f === 'manifest.webmanifest')
  .map((f) => `/${f}`);
const precache = ['/', ...statics.sort(), ...assets.sort()];

// Version follows content: the hashed asset names capture the code and the
// content; index.html captures everything else (it references the entry).
const version = createHash('sha256')
  .update(precache.join('\n'))
  .update(readFileSync(join(DIST, 'index.html')))
  .digest('hex')
  .slice(0, 12);

const sw = `// generated by scripts/build-sw.mjs — do not edit
const CACHE = 'meshit30-${version}';
const PRECACHE = ${JSON.stringify(precache, null, 1)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== location.origin) return;

  // Navigations go network-first so a new deploy is picked up when online;
  // offline falls back to the cached shell.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone();
          caches.open(CACHE).then((cache) => cache.put('/', copy));
          return response;
        })
        .catch(() => caches.match('/')),
    );
    return;
  }

  // Everything else is cache-first: hashed assets are immutable by name.
  event.respondWith(
    caches.match(request).then(
      (hit) =>
        hit ??
        fetch(request).then((response) => {
          if (response.ok) {
            const copy = response.clone();
            caches.open(CACHE).then((cache) => cache.put(request, copy));
          }
          return response;
        }),
    ),
  );
});
`;

writeFileSync(join(DIST, 'sw.js'), sw);
console.log(`✓ dist/sw.js — cache meshit30-${version}, ${precache.length} precached files`);
