import { StrictMode, Suspense, lazy } from 'react';
import { createRoot } from 'react-dom/client';
import App from './App.jsx';
import './styles.css';

// The local content admin exists only on the dev server: this condition is a
// constant false in a production build, so the screen is never even bundled.
const Admin = import.meta.env.DEV && window.location.pathname.startsWith('/admin')
  ? lazy(() => import('./screens/Admin.jsx'))
  : null;

createRoot(document.getElementById('root')).render(
  <StrictMode>
    {Admin ? <Suspense fallback={null}><Admin /></Suspense> : <App />}
  </StrictMode>,
);

// Offline support: dist/sw.js is generated by scripts/build-sw.mjs at build
// time with the full precache list, so it exists only in production builds.
if (import.meta.env.PROD && 'serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/sw.js').catch(() => {
      // Offline is an enhancement; a failed registration must not break the app.
    });
  });
}
